[workspace]
members = [
    "oauth2-cli",
    "oauth2-client",
    "oauth2-core",
    "oauth2-lite",
    "oauth2-server",
    "oauth2-signin",
    "oauth2-signin/integrations/*",
    #
    "providers/*",
    #
    "examples/client/*",
]
