[package]
name = "oauth2_client_web_app_flow_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
oauth2-client = { version = "^0.0", path = "../oauth2-client", default-features = false, features = ["with-authorization-code-grant", "with-flow", "with-user-info"] }

oauth2-github = { version = "^0.0", path = "../providers/oauth2-github", default-features = false, features = ["with-authorization-code-grant", "with-user-info"] }
oauth2-google = { version = "^0.0", path = "../providers/oauth2-google", default-features = false, features = ["with-authorization-code-grant", "with-user-info"] }

tokio = { version = "1.12", default-features = false, features = ["macros", "rt-multi-thread"] }
http-api-isahc-client = { version = "0.1" }

warp = { version = "0.3", default-features = false, features = ["tls"] }
futures-util = { version = "0.3" }

serde = { version = "1.0", default-features = false, features = ["derive"] }
toml = { version = "0.5" }

pretty_env_logger = { version = "0.4" }
log = { version = "0.4" }
